# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ftp-server" do |ftp|
    ftp.vm.hostname = "ftp.isrv.test"
    ftp.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "dns-server" do |dns|
    dns.vm.hostname = "dns.isrv.test"
    dns.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.provision "ansible", run: "once" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/hosts.ini"
    ansible.limit = "all"
  end
end
